#!/usr/local/bin/zsh
cd /electrs
#source $HOME/.cargo/env
#export PATH=$HOME/.cargo/bin:$PATH

until false
do
	cargo run \
		--release \
		--features liquid \
		--bin electrs \
		-- \
		-vvv \
		--address-search \
		--cors '*' \
		--network liquid \
		--daemon-dir /elements \
		--http-addr '[::]:3001' \
		--monitoring-addr '127.0.0.1:4225' \
		--cookie 'user:pass' \
		--precache-scripts $HOME/electrs/contrib/popular-scripts.txt
	sleep 1
done
