#!/usr/local/bin/zsh
cd "${HOME}/electrs"
#source "${HOME}/.cargo/env"
#export PATH="${HOME}/.cargo/bin:${PATH}"

until false
do
	cargo run \
		--release \
		--features liquid \
		--bin electrs \
		-- \
		-vv \
		--asset-db-path "${HOME}/asset_registry_testnet_db" \
		--address-search \
		--cors '*' \
		--db-dir __ELECTRS_DATA_ROOT__ \
		--network liquidtestnet \
		--daemon-dir "${HOME}" \
		--http-addr '[::]:3004' \
		--cookie '__ELEMENTS_RPC_USER__:__ELEMENTS_RPC_PASS__' \
		--precache-scripts "${HOME}/electrs/contrib/popular-scripts.txt"
	sleep 1
done
