#!/usr/local/bin/zsh
cd /electrs
source $HOME/.cargo/env
export PATH=$HOME/.cargo/bin:$PATH

until false
do
	cargo run \
		--release \
		--bin electrs \
		-- \
		-vv \
		--network testnet \
		--daemon-dir /bitcoin \
		--http-addr '[::]:3002' \
		--cookie 'user:pass' \
		--precache-scripts /electrs/contrib/popular-scripts.txt
	sleep 1
done
