#!/usr/bin/env zsh
cd "${HOME}/electrs"
#source $HOME/.cargo/env
#export PATH=$HOME/.cargo/bin:$PATH

until false
do
	cargo run \
		--release \
		--bin electrs \
		-- \
		-vvvv \
		--network testnet \
		--address-search \
		--cors '*' \
		--db-dir __ELECTRS_DATA_ROOT__ \
		--daemon-dir "${HOME}" \
		--http-socket-file '/bitcoin/socket/esplora-bitcoin-testnet' \
		--cookie '__BITCOIN_RPC_USER__:__BITCOIN_RPC_PASS__' \
		--precache-scripts "${HOME}/electrs/contrib/popular-scripts.txt"

	sleep 3
done
