#!/usr/local/bin/zsh
cd $HOME/electrs
#source $HOME/.cargo/env
#export PATH=$HOME/.cargo/bin:$PATH

until false
do
	cargo run \
		--release \
		--bin electrs \
		-- \
		-vvvv \
		--network testnet \
		--cors '*' \
		--db-dir /electrs \
		--daemon-dir $HOME \
		--http-addr '[::]:3002' \
		--cookie 'user:pass' \
		--precache-scripts $HOME/electrs/contrib/popular-scripts.txt

	sleep 3
done
