#!/usr/local/bin/zsh
cd "$HOME/electrs"
#source $HOME/.cargo/env
#export PATH=$HOME/.cargo/bin:$PATH

until false
do
	# patch code for FreeBSD
	if grep XBS5 "$HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/sysconf-0.3.4/src/raw.rs" ; then
		grep -v XBS5 $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/sysconf-0.3.4/src/raw.rs > /tmp/foo && \
		mv /tmp/foo $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/sysconf-0.3.4/src/raw.rs
	fi

	cargo run \
		--release \
		--features liquid \
		--bin electrs \
		-- \
		-vv \
		--asset-db-path "$HOME/asset_registry_testnet_db" \
		--address-search \
		--cors '*' \
		--db-dir /electrs \
		--network liquidtestnet \
		--daemon-dir $HOME \
		--http-addr '[::]:3004' \
		--cookie 'foo:bar' \
		--precache-scripts $HOME/electrs/contrib/popular-scripts.txt
	sleep 1
done
