#!/usr/bin/env zsh
set -e

export NVM_DIR="$HOME/.nvm"
source "$NVM_DIR/nvm.sh"

# pin node/npm to the versions tracked in the repo
NODE_VERSION=$(cat "${HOME}/mempool/.nvmrc")
NPM_VERSION=$(cat "${HOME}/mempool/.npm-version")

if [ -z "${NPM_VERSION}" ] || [ -z "${NODE_VERSION}" ]; then
    echo "[!] Missing node/npm version in ${HOME}/mempool/[.nvmrc | .npm-version]" >&2
    exit 1
fi

if ! nvm use "${NODE_VERSION}";then
    echo "[!] node ${NODE_VERSION} not installed; run: nvm install ${NODE_VERSION} --shared-zlib" >&2
    exit 1
fi

if [ "$(npm -v)" != "${NPM_VERSION}" ];then
    npm install -g "npm@${NPM_VERSION}" || exit 1
fi

echo "Using versions of node/npm: "
echo "node: $(node -v)"
echo "npm: $(npm -v)"

cd "$HOME/liquid/frontend"
npm run sync-assets

rsync -av "$HOME/liquid/frontend/dist/mempool/browser/resources/assets"* "$HOME/public_html/liquid/resources/"
