#!/usr/bin/env zsh

echo restarting all mempool backends | wall
echo restarting all mempool backends | logger -t mempool -p local7.notice
ps uaxw|grep 'dist/index'|grep -v grep|grep -v services|awk '{print $2}'|xargs -n 1 kill

exit 0
