#!/usr/local/bin/zsh -x
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:$HOME/bin

if [ -f $HOME/lock ];then
    echo "check lockfile"
    exit 1
fi

touch $HOME/lock

export NVM_DIR="$HOME/.nvm"
source "$NVM_DIR/nvm.sh"

REPO=origin
BRANCH=master
if [ ! -z "$1" ];then
    BRANCH=$1
fi
echo "upgrading mempool to ${BRANCH}" | wall

cd "$HOME/mempool"
git fetch "${REPO}"
git reset --hard "${REPO}/${BRANCH}"
cd "$HOME/"

for site in mainnet liquid testnet bisq
do
    cd "$HOME/${site}"
    git fetch "${REPO}"
    git reset --hard "${REPO}/${BRANCH}"
    hash=$(git rev-parse HEAD)

    if [ "${site}" = "mainnet" ]
    then
        cd "$HOME/${site}/frontend"
        npm install --only=prod
        npm run build
        rsync -av ./dist/mempool/* "${HOME}/public_html/${site}/"
    fi

    cd "$HOME/${site}/backend"
    npm install --only=prod
    npm run build
done

hostname=$(hostname)
keybase chat send --channel dev mempool "${hostname} updated to ${hash}"

rm "$HOME/lock"
