#!/usr/local/bin/zsh
for site in mainnet liquid testnet
do
    git clone https://github.com/mempool/mempool "${HOME}/${site}"
    mkdir -p "${HOME}/public_html/${site}/"
    cd "${HOME}/${site}/backend/"
    cp "../production/mempool-config.${site}.json" "mempool-config.json"
    touch cache.json
    npm install
    npm run build
    cd "${HOME}/${site}/frontend/"
    npm install
    npm run build
done
