#!/usr/local/bin/zsh
export NVM_DIR="$HOME/.nvm"
source "$NVM_DIR/nvm.sh"
for site in mainnet liquid testnet bisq signet liquidtestnet
do
    #git clone https://github.com/mempool/mempool "${HOME}/${site}"
    mkdir -p "${HOME}/public_html/${site}/"

    cd "${HOME}/${site}/backend/"
    cp "${HOME}/mempool/production/mempool-config.${site}.json" "mempool-config.json"

    npm install
    npm run build

    if [ "${site}" = "mainnet" ]
    then
        cd "${HOME}/${site}/frontend/"
        cp "${HOME}/mempool/production/mempool-frontend-config.${site}.json" "mempool-frontend-config.json"
        npm install
        npm run build
        rsync -av ./dist/mempool/browser/* "${HOME}/public_html/${site}/"
    fi
done
