#!/usr/bin/env zsh
hostname=$(hostname)
while true
do for url in / \
	'/api/v1/statistics/2h' \
	'/api/v1/statistics/24h' \
	'/api/v1/statistics/1w' \
	'/api/v1/statistics/1m' \
	'/api/v1/statistics/3m' \
	'/api/v1/statistics/6m' \
	'/api/v1/statistics/1y' \
	'/api/v1/statistics/2y' \
	'/api/v1/statistics/3y' \
	'/api/v1/mining/pools?interval=24h' \
	'/api/v1/mining/pools?interval=3d' \
	'/api/v1/mining/pools?interval=1w' \
	'/api/v1/mining/pools?interval=1m' \
	'/api/v1/mining/pools?interval=3m' \
	'/api/v1/mining/pools?interval=6m' \
	'/api/v1/mining/pools?interval=1y' \
	'/api/v1/mining/pools?interval=2y' \
	'/api/v1/mining/pools?interval=3y' \

	do
		curl -s "https://${hostname}${url}" >/dev/null
	done

	sleep 10
done
