#!/usr/bin/env zsh
hostname=$(hostname)
while true
do for url in / \
	'/api/v1/statistics/2h' \
	'/api/v1/statistics/24h' \
	'/api/v1/statistics/1w' \
	'/api/v1/statistics/1m' \
	'/api/v1/statistics/3m' \
	'/api/v1/statistics/6m' \
	'/api/v1/statistics/1y' \
	'/api/v1/statistics/2y' \
	'/api/v1/statistics/3y' \
	'/api/v1/mining/pools/24h' \
	'/api/v1/mining/pools/3d' \
	'/api/v1/mining/pools/1w' \
	'/api/v1/mining/pools/1m' \
	'/api/v1/mining/pools/3m' \
	'/api/v1/mining/pools/6m' \
	'/api/v1/mining/pools/1y' \
	'/api/v1/mining/pools/2y' \
	'/api/v1/mining/pools/3y' \
	'/api/v1/mining/pools/all' \
	'/api/v1/mining/hashrate/3m' \
	'/api/v1/mining/hashrate/6m' \
	'/api/v1/mining/hashrate/1y' \
	'/api/v1/mining/hashrate/2y' \
	'/api/v1/mining/hashrate/3y' \
	'/api/v1/mining/hashrate/all' \
	'/api/v1/mining/hashrate/pools/3m' \
	'/api/v1/mining/hashrate/pools/6m' \
	'/api/v1/mining/hashrate/pools/1y' \
	'/api/v1/mining/hashrate/pools/2y' \
	'/api/v1/mining/hashrate/pools/3y' \
	'/api/v1/mining/hashrate/pools/all' \
	'/api/v1/mining/reward-stats/144' \

	do
		curl -s "https://${hostname}${url}" >/dev/null
	done

	slugs=$(cat pools.json | jq -r .slugs[])
	for slug in $slugs
	do
		curl -s "https://${hostname}/api/v1/mining/pool/${slug}/hashrate" >/dev/null
		curl -s "https://${hostname}/api/v1/mining/pool/${slug}" >/dev/null
	done

	sleep 10
done
