/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class GbtGenerator {
  constructor()
  make(mempoolBuffer: Uint8Array): Promise<GbtResult>
  update(newTxs: Uint8Array, removeTxs: Uint8Array): Promise<GbtResult>
}
/**
 * The result from calling the gbt function.
 *
 * This tuple contains the following:
 *   blocks: A 2D Vector of transaction IDs (u32), the inner Vecs each represent a block.
 * clusters: A 2D Vector of transaction IDs representing clusters of dependent mempool transactions
 *    rates: A Vector of tuples containing transaction IDs (u32) and effective fee per vsize (f64)
 */
export class GbtResult {
  blocks: Array<Array<number>>
  clusters: Array<Array<number>>
  rates: Array<Array<number>>
  constructor(blocks: Array<Array<number>>, clusters: Array<Array<number>>, rates: Array<Array<number>>)
}
