/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function make(mempoolBuffer: Uint8Array, callback: (arg0: GbtResult) => void): void
export function update(newTxs: Uint8Array, removeTxs: Uint8Array, callback: (arg0: GbtResult) => void): void
export class GbtResult {
  blocks: Array<Array<number>>
  clusters: Array<Array<number>>
  rates: Array<Array<number>>
  constructor(blocks: Array<Array<number>>, clusters: Array<Array<number>>, rates: Array<Array<number>>)
}
