// Lightning feature bit names.
// Source: https://github.com/lightning/bolts/blob/master/09-features.md
export const FeaturesMap = new Map<number, string>([
  [0, 'data-loss-protect'],
  [1, 'data-loss-protect'],
  [3, 'initial-routing-sync'],
  [4, 'upfront-shutdown-script'],
  [5, 'upfront-shutdown-script'],
  [6, 'gossip-queries'],
  [7, 'gossip-queries'],
  [8, 'tlv-onion'],
  [9, 'tlv-onion'],
  [12, 'static-remote-key'],
  [13, 'static-remote-key'],
  [14, 'payment-addr'],
  [15, 'payment-addr'],
  [16, 'multi-path-payments'],
  [17, 'multi-path-payments'],
  [18, 'wumbo-channels'],
  [19, 'wumbo-channels'],
  [20, 'anchor-commitments'],
  [21, 'anchor-commitments'],
  [22, 'anchors-zero-fee-htlc-tx'],
  [23, 'anchors-zero-fee-htlc-tx'],
  [26, 'shutdown-any-segwit'],
  [27, 'shutdown-any-segwit'],
  [30, 'amp'],
  [31, 'amp'],
  [44, 'explicit-commitment-type'],
  [45, 'explicit-commitment-type'],
  [46, 'scid-alias'],
  [47, 'scid-alias'],
  [48, 'payment-metadata'],
  [49, 'payment-metadata'],
  [50, 'zero-conf'],
  [51, 'zero-conf'],
  [54, 'keysend'],
  [55, 'keysend'],
  [80, 'taproot-channels'],
  [81, 'taproot-channels'],
  [180, 'taproot-channels-staging'],
  [181, 'taproot-channels-staging'],
  [2022, 'script-enforced-lease'],
  [2023, 'script-enforced-lease'],
]);
