name: 'Check if servers are in sync'

on: [workflow_dispatch]

permissions:
  contents: read

jobs:
  print-backend-sha:
    runs-on: mempool-ci
    name: Get block height
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          path: repo

      - name: Run script
        working-directory: repo
        run: |
          chmod +x ./scripts/get_block_tip_height.sh
          sh ./scripts/get_block_tip_height.sh
