name: 'Print images digest'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image Version'
        required: false
        default: 'latest'
        type: string

permissions:
  contents: read

jobs:
  print-images-sha:
    runs-on: mempool-ci
    name: Print digest for images
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: digest

      - name: Run script
        working-directory: digest
        run: |
          sh ./docker/scripts/get_image_digest.sh $VERSION
        env: 
          VERSION: ${{ github.event.inputs.version }}
