name: Project Board Automation

on:
  pull_request:
    types: [review_requested]
  issues:
    types: [opened]

jobs:
  project-automation:
    uses: mempool/.github/.github/workflows/project-board-automation.yml@master
    with:
      project-number: 8
    secrets:
      PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      STATUS_FIELD_ID: ${{ secrets.STATUS_FIELD_ID }}
      REVIEW_NEEDED_OPTION_ID: ${{ secrets.REVIEW_NEEDED_OPTION_ID }}